// <auto-generated />
namespace Pook.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NoteUpdatUserIdToStringAddIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoteUpdatUserIdToStringAddIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201605290946110_NoteUpdatUserIdToStringAddIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
